# Use the official MongoDB image
FROM mongo:latest

# Copy the initialization script
#COPY ms.mongo.worktimerecord.db/init.js /docker-entrypoint-initdb.d/
#COPY ["./init.js", "/docker-entrypoint-initdb.d/"]