name: Trigger auto deployment for auditory

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'API.Auditory/**'
    - '.github/workflows/auditory-AutoDeployTrigger-cc200462-4e93-4dcb-b387-bff2aaa54ea7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AUDITORY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AUDITORY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AUDITORY_AZURE_SUBSCRIPTION_ID }}
      - name: Build and push container image to registry
        run: |
          docker build -t ramonserranosopra/auditoryapi:${{ github.sha }} -f Dockerfile ../
          echo ${{ secrets.AUDITORYAPI_REGISTRY_PASSWORD }} | docker login docker.io -u ${{ secrets.AUDITORYAPI_REGISTRY_USERNAME }} --password-stdin
          docker push ramonserranosopra/auditoryapi:${{ github.sha }}
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/API.Auditory
          registryUrl: docker.io
          registryUsername: ${{ secrets.AUDITORY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AUDITORY_REGISTRY_PASSWORD }}
          containerAppName: auditory
          resourceGroup: Borrar2
          imageToBuild: ramonserranosopra/auditory:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


