name: Trigger auto deployment for worktimerecord

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/worktimerecord-AutoDeployTrigger-3a4692e1-abce-499d-ba05-c4e0e5e5ffc8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WORKTIMERECORD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WORKTIMERECORD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WORKTIMERECORD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.WORKTIMERECORD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WORKTIMERECORD_REGISTRY_PASSWORD }}
          containerAppName: worktimerecord
          resourceGroup: Borrar2
          imageToBuild: ramonserranosopra/worktimerecord:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


